name: project_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0

  shared_preferences: ^2.2.2
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "C:/Users/Parsian/Downloads/Icon_Of_Program.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/